debug: true
server:
  port: 8083

spring:
  datasource:
    username: root
    password: Accton123@
    url: jdbc:mysql://localhost:3306/newframework

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: always

  ldap:
    urls: ldap://ldap.accton.com.vn:389
    base: OU=acctonvn,DC=acctonvn,DC=local
    username: vn_agile_admin
    password: 5k$ZzHKrA#QE

ldap-config:
  vn:
    urls: ldap://ldap.accton.com.vn:389
    base: OU=acctonvn,DC=acctonvn,DC=local
    username: vn_agile_admin
    password: 5k$ZzHKrA#QE

  jt:
    urls: ldap://ldap.accton.com.vn:389
    base: OU=acctonvn,DC=acctonvn,DC=local
    username: vn_agile_admin
    password: 5k$ZzHKrA#QE

  ac:
    urls: ldap://hqldap.accton.com:389
    base: OU=acctonvn,DC=acctonvn,DC=local
    username: agile_admin
    password: Raise$alary@ccton202311

jwt:
  secret: heladslkasdaskdlasdjldasldaslkdasdlaskdalkdjlkasjldkjaslk
  expiration: 1