debug: true
server:
  port: 8083

spring:
  datasource:
    username: root
    password: Accton123@
    url: jdbc:mysql://localhost:3306/agile_db

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always

  ldap:
    urls: ldap://ldap.accton.com.vn:389
    base: OU=acctonvn,DC=acctonvn,DC=local
    username: vn_agile_admin
    password: 5k$ZzHKrA#QE
