debug: true
server:
  port: 8083

spring:
  datasource:
    username: root
    password: Accton123@
    url: jdbc:mysql://localhost:3306/agile_db

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always

